name: worksave
description: "WorkSave - Save trang thai lam viec nhu game, note y tuong, gen prompt bao cao tuan."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.3.3
  path_provider: ^2.1.4
  path: ^1.9.0
  meta: ^1.15.0
  http: ^1.2.2
  local_notifier: ^0.1.6
  window_manager: ^0.4.3
  tray_manager: ^0.2.4
  hotkey_manager: ^0.2.3
  launch_at_startup: ^0.3.1
  confetti: ^0.8.0
  file_selector: ^1.0.3

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tray_icon.ico
